export const LOAD_CONTACTS = "LOAD_CONTACTS";
export const FAIL_CONTACTS = "FAIL_CONTACTS";

export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACT = "GET_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const POST_CONTACT = "POST_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
